---

- name: get uid of ticket grantee
  command: id -u {{maprlogin_username}}
  register: uid
  changed_when: false

- name: obtain a MapR service ticket for a user
  sudo: yes
  sudo_user: "{{mapr_admin_username}}"
  shell: maprlogin generateticket -type service -user {{maprlogin_username}} -out /tmp/maprticket_{{uid.stdout}} -duration {{duration}}
  args:
    creates: /tmp/maprticket_{{uid.stdout}}

- name: change ownership of service ticket
  sudo: yes
  sudo_user: root
  file: state=file path=/tmp/maprticket_{{uid.stdout}} owner={{maprlogin_username}}
